### ISSUE TITLE
add header on file upload

### ISSUE THREAD

**Issue by stefanchiriac** [guillermomartinez/filemanager-ui#1]
Hello,

I have a global csrf header on all ajax requests and it works in all cases, except when I try to upload a file.  There is any way to add the header on file upload?

Looking through `filemanage-ui-without.js` I found where the headers are being set, but I can't figure out how I can setup `this.options.headers` without modifying the file

```
headers = {
        "Accept": "application/json",
        "Cache-Control": "no-cache",
        "X-Requested-With": "XMLHttpRequest"
      };
      if (this.options.headers) {
        extend(headers, this.options.headers);
      }
```

Thanks

**Comment by stefanchiriac** [comment]
a way of adding header on upload I find it to be on jquery.filemanager.js >  dropzone initialization.

```
var myDropzone = new Dropzone("#"+ filemanager.attr("id"), {
     headers: settings.headers
```

**Comment by guillermomartinez** [comment]
Update to [0.1.5](https://github.com/guillermomartinez/filemanager-ui/releases/tag/0.1.5)
