### ISSUE TITLE
integration with other framework

### ISSUE THREAD

**Issue by rakucmr** [guillermomartinez/filemanager-ui#10]
Hello,
Can you tell me please json format and post/get format so I can write other file manager controller.

Thanks.

**Comment by admont28** [comment]
Hello,
You don't need Laravel Framework to integrate in your project, check this documentation: http://php-filemanager.rhcloud.com -> Installation of Filemanager for PHP.

**Comment by guillermomartinez** [comment]
Updated documentation https://github.com/guillermomartinez/filemanager-ui/wiki

**Comment by guillermomartinez** [comment]
If you want to create another connector for another language you have to guide the original connector [filemanager-php](https://github.com/guillermomartinez/filemanager-php/blob/master/src/GuillermoMartinez/Filemanager/Filemanager.php#L53)

**Comment by rakucmr** [comment]
Thanks, I will try and I will send you the result :)
